name: Classic Bug Report
description: Report a bug in ElvUI for Classic WoW
title: "[Classic Bug Report] <Title here>"
labels: [':bug::question: Bug (Needs Investigation)', ':video_game: Classic']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue you are having?
      description: Describe the issue and what was going on when it happened?
      placeholder: Give us an explaination of what was going on when the issue appeared.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: What do you think the expected behavior should have happened?
      placeholder: Try to explain what you expected the outcome to be.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: What actually happened?
      description: Please try to be as descriptive as possible.
      placeholder: Try to explain what happened.
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution/Workaround
      description: If you have any idea how we could solve it let us know.
      placeholder: "Make sure type the command: /edebug on then test."
    validations:
      required: false
  - type: textarea
    id: errors
    attributes:
      label: Errors
      description: If you have any errors, please put them here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: ElvUI Changelog/Troubleshooting
      description: By submitting this issue, you agree you followed our [Troubelshooting Steps](https://urlfortroubleshootingstepshere.com)
      options:
        - label: I have confirmed that I have read the [Changelog](https://changelogurlhere.com) and done the [Troubelshooting Steps](https://urlfortroubleshootingstepshere.com).
          required: true
  - type: checkboxes
    id: term
    attributes:
      label: ElvUI Troubleshooting
      description: By submitting this issue, you agree you followed our [Troubelshooting Steps](https://urlfortroubleshootingstepshere.com)
      options:
        - label: I have confirmed that I have read the [Changelog](https://changelogurlhere.com) and done the [Troubelshooting Steps](https://urlfortroubleshootingstepshere.com).
          required: true