name: Release

on:
  push:
    # branches:
    #   - dev
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v1
        with:
          fetch-depth: 100
      - name: Release Job
        uses: BigWigsMods/packager@master
      # - name: Classic
      #   uses: BigWigsMods/packager@master
      #   with:
      #     args: -g classic
      # - name: Burning Crusade Classic
      #   uses: BigWigsMods/packager@master
      #   with:
      #     args: -g bcc
